### ISSUE TITLE
consul 集群时，yml文件如何配置？

### ISSUE THREAD

**Issue by jiangcaijun** [yidongnan/spring-cloud-consul-example#7]
如题，
```
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
```
当consul 为集群时，yml文件如何配置？看目前这个配置文件，只支持单点的

求教，谢谢
